// ignore_for_file: constant_identifier_names

abstract final class SettingBoxKey {
  static const String btmProgressBehavior = 'btmProgressBehavior',
      defaultVideoQa = 'defaultVideoQa',
      defaultVideoQaCellular = 'defaultVideoQaCellular',
      defaultVideoQaHalfScreen = 'defaultVideoQaHalfScreen',
  videoPlayerSwitchForceTimeoutSeconds =
    'videoPlayerSwitchForceTimeoutSeconds',
      defaultAudioQa = 'defaultAudioQa',
      defaultAudioQaCellular = 'defaultAudioQaCellular',
      autoPlayEnable = 'autoPlayEnable',
      fullScreenMode = 'fullScreenMode',
      preferCodecs = 'preferCodecs',
      defaultToastOp = 'defaultToastOp',
      defaultPicQa = 'defaultPicQa',
      enableHA = 'enableHA',
      audioOutput = 'audioOutput',
      bufferSize = 'bufferSize',
      bufferSec = 'bufferSec',
      hardwareDecoding = 'hardwareDecoding',
      videoSync = 'videoSync',
      autosync = 'autosync',
      customMpvOptions = 'customMpvOptions',
      mpvLogLevel = 'mpvLogLevel',
      useMpvVideoScaling = 'useMpvVideoScaling',
      coverFullscreenTransitionWithBlack =
          'coverFullscreenTransitionWithBlack',
      p1080 = 'p1080',
      enableAutoEnter = 'enableAutoEnter',
      enableAutoExit = 'enableAutoExit',
      enableOnlineTotal = 'enableOnlineTotal',
      superChatType = 'superChatType',
      fullScreenSCWidth = 'fullScreenSCWidth',
      keyboardControl = 'keyboardControl',
      pauseOnMinimize = 'pauseOnMinimize',
      pgcSkipType = 'pgcSkipType',
      audioPlayMode = 'audioPlayMode',
      showBatteryLevel = 'showBatteryLevel',
      showBatteryPercentage = 'showBatteryPercentage',
      showMpvOutputFps = 'showMpvOutputFps',
      showBufferingInfo = 'showBufferingInfo',
      showPlayerInstanceStatus = 'showPlayerInstanceStatus',
      playerVolume = 'playerVolume',
      maxVolume = 'maxVolume';

  static const String enableVerticalExpand = 'enableVerticalExpand',
    feedBackEnable = 'feedBackEnable',

    // 旧版布尔设置，保留用于兼容已有用户。
    enableLongShowControl = 'enableLongShowControl',

    // 播放控件无操作后自动隐藏的秒数。
    playerControlDisplayDurationSeconds =
        'playerControlDisplayDurationSeconds',

      horizontalScreen = 'horizontalScreen',
      CDNService = 'CDNService',
      CDNServices = 'CDNServices',
      cdnRotationIndex = 'cdnRotationIndex',
      disableAudioCDN = 'disableAudioCDN',
      autoPiP = 'autoPiP',
      enableAutoLongPressSpeed = 'enableAutoLongPressSpeed',
      showLongPressSpeedToast = 'showLongPressSpeedToast',
      longPressSpeedTriggerDelay = 'longPressSpeedTriggerDelay',
      useRelativeSlide = 'useRelativeSlide',
      sliderDuration = 'sliderOffset',
      horizontalSeekGestureThreshold = 'horizontalSeekGestureThreshold',
      enableQuickDouble = 'enableQuickDouble',
      fullScreenGestureReverse = 'fullScreenGestureReverse',
      enableBackgroundPlay = 'enableBackgroundPlay',
      continuePlayInBackground = 'continuePlayInBackground',
      appRcmd = 'appRcmd',
rcmdRefreshCount = 'rcmdRefreshCount',
showRecommendRefreshStatsToast = 'showRecommendRefreshStatsToast',
recommendHistoryFilterSettings = 'recommendHistoryFilterSettings',
enableSaveLastData = 'enableSaveLastData',
      minDurationForRcmd = 'minDurationForRcmd',
      minPlayForRcmd = 'minPlayForRcmd',
      minLikeRatioForRecommend = 'minLikeRatioForRecommend',
      exemptFilterForFollowed = 'exemptFilterForFollowed',
      banWordForRecommend = 'banWordForRecommend',
      applyFilterToRelatedVideos = 'applyFilterToRelatedVideos',
      autoUpdate = 'autoUpdate',
      maxCacheSize = 'maxCacheSize',
      defaultShowComment = 'defaultShowComment',
      replySortType = 'replySortType',
      defaultDynamicType = 'defaultDynamicType',
      showDynInteraction = 'showDynInteraction',
      enableHotKey = 'enableHotKey',
      enableSearchRcmd = 'enableSearchRcmd',
      enableQuickFav = 'enableQuickFav',
      enableWordRe = 'enableWordRe',
      enableSearchWord = 'enableSearchWord',
      enableSystemProxy = 'enableSystemProxy',
      enableAi = 'enableAi',
      disableLikeMsg = 'disableLikeMsg',
      defaultHomePage = 'defaultHomePage',
      previewQuality = 'previewQuality',
      checkDynamic = 'checkDynamic',
      dynamicPeriod = 'dynamicPeriod',
      schemeVariant = 'schemeVariant',
      showViewPoints = 'showViewPoints',
      showRelatedVideo = 'showRelatedVideo',
      showVideoReply = 'showVideoReply',
      showBangumiReply = 'showBangumiReply',
      alwaysExpandIntroPanel = 'alwaysExapndIntroPanel',
      expandIntroPanelH = 'exapndIntroPanelH',
      horizontalSeasonPanel = 'horizontalSeasonPanel',
      horizontalMemberPage = 'horizontalMemberPage',
      replyLengthLimit = 'replyLengthLimit',
      showArgueMsg = 'showArgueMsg',
      reverseFromFirst = 'reverseFromFirst',
      badCertificateCallback = 'badCertificateCallback',
      continuePlayingPart = 'continuePlayingPart',
      cdnSpeedTest = 'cdnSpeedTest',
      horizontalPreview = 'horizontalPreview',
      banWordForReply = 'banWordForReply',
      banWordForZone = 'banWordForZone',
      savedRcmdTip = 'savedRcmdTip',
      openInBrowser = 'openInBrowser',
      videoDetailUseAv = 'videoDetailUseAv',
      externalVideoLinkOpenInDetail = 'externalVideoLinkOpenInDetail',
      openClipboardLinkOnResume = 'openClipboardLinkOnResume',
      refreshHomeOnRestart = 'refreshHomeOnRestart',
      showMineQuote = 'showMineQuote',
      refreshDragPercentage = 'refreshDragPercentage',
      refreshDisplacement = 'refreshDisplacement',
      showHotRcmd = 'showHotRcmd',
      audioNormalization = 'audioNormalization',
      fallbackNormalization = 'fallbackNormalization',
      superResolutionType = 'superResolutionType',
      preInitPlayer = 'preInitPlayer',
      preloadVideoShot = 'preloadVideoShot',
      mainTabBarView = 'mainTabBarView',
      searchSuggestion = 'searchSuggestion',
      showDecorate = 'showDynDecorate',
      showMedal = 'showMedal',
      enableLivePhoto = 'enableLivePhoto',
      showSeekPreview = 'showSeekPreview',
      showSeekPreviewOnSlider = 'showSeekPreviewOnSlider',
      showSeekPreviewOnGesture = 'showSeekPreviewOnGesture',
      seekTimeInPreview = 'seekTimeInPreview',
      biliProgressTimeStyle = 'biliProgressTimeStyle',
      playerProgressThumbScale = 'playerProgressThumbScale',
      playerProgressBarTouchPadding = 'playerProgressBarTouchPadding',
      playerControlHorizontalPadding = 'playerControlHorizontalPadding',
      playerControlBarThicknessScale = 'playerControlBarThicknessScale',
      playerControlBarGradientExtent = 'playerControlBarGradientExtent',
      seekPreviewFollowSlider = 'seekPreviewFollowSlider',
seekPreviewFollowGesture = 'seekPreviewFollowGesture',
seekPreviewScale = 'seekPreviewScale',
      seekPreviewProgressBarGap = 'seekPreviewProgressBarGap',
      showSeekPreviewInNonFullscreen = 'showSeekPreviewInNonFullscreen',
      showDmChart = 'showDmChart',
      enableCommAntifraud = 'enableCommAntifraud',
      biliSendCommAntifraud = 'biliSendCommAntifraud',
      enableCreateDynAntifraud = 'enableCreateDynAntifraud',
      coinWithLike = 'coinWithLike',
      isPureBlackTheme = 'isPureBlackTheme',
      antiGoodsDyn = 'antiGoodsDyn',
      antiGoodsReply = 'antiGoodsReply',
      expandDynLivePanel = 'expandDynLivePanel',
      springDescription = 'springDescription',
      enableHttp2 = 'enableHttp2',
      slideDismissReplyPage = 'slideDismissReplyPage',
      showFSActionItem = 'showFSActionItem',
      enableShrinkVideoSize = 'enableShrinkVideoSize',
      showDynActionBar = 'showDynActionBar',
      darkVideoPage = 'darkVideoPage',
      enableSlideVolumeBrightness = 'enableSlideVolumeBrightness',
      pinchGestureAngleThreshold = 'pinchGestureAngleThreshold',
      volumeGestureAngleThreshold = 'volumeGestureAngleThreshold',
      brightnessGestureAngleThreshold = 'brightnessGestureAngleThreshold',
      volumeGestureSpeed = 'volumeGestureSpeed',
      brightnessGestureSpeed = 'brightnessGestureSpeed',
      // 保留旧字符串值，已有用户设置无需迁移。
      volumeBrightnessGestureProgressBar = 'volumeGestureProgressBar',
      playerGestureToastVerticalPercent = 'playerGestureToastVerticalPercent',
      playerGestureToastFontSize = 'playerGestureToastFontSize',
      seekTimeToastVerticalPercent = 'seekTimeToastVerticalPercent',
      longPressSpeedToastVerticalPercent =
          'longPressSpeedToastVerticalPercent',
      seekTimeToastFontSize = 'seekTimeToastFontSize',
      longPressSpeedToastFontSize = 'longPressSpeedToastFontSize',
      enableSlideFS = 'enableSlideFS',
      retryCount = 'retryCount',
      retryDelay = 'retryDelay',
      liveQuality = 'liveQuality',
      liveQualityCellular = 'liveQualityCellular',
      appFontWeight = 'appFontWeight',
      appChineseFontFile = 'appChineseFontFile',
      appChineseFontName = 'appChineseFontName',
      appEnglishFontFile = 'appEnglishFontFile',
      appEnglishFontName = 'appEnglishFontName',
      fastForBackwardDuration = 'fastForBackwardDuration',
      recordSearchHistory = 'recordSearchHistory',
      autoHistoryArchive = 'autoHistoryArchive',
      historyArchiveIntervalDays = 'historyArchiveIntervalDays',
      silentHistoryArchive = 'silentHistoryArchive',
      showPgcTimeline = 'showPgcTimeline',
      pageTransition = 'pageTransition',
      optTabletNav = 'optTabletNav',
      banWordForDyn = 'banWordForDyn',
      enableLog = 'enableLog',
      memberTab = 'memberTab',
      dynamicDetailRatio = 'dynamicDetailRatio',
      directExitOnBack = 'directExitOnBack',
      quickFavId = 'quickFavId',
      showFsScreenshotBtn = 'showFsScreenshotBtn',
      showFsLockBtn = 'showFsLockBtn',
      showFsSkipOpBtn = 'showFsSkipOpBtn',
      skipOpDurationSeconds = 'skipOpDurationSeconds',
      silentDownImg = 'silentDownImg',
      showMemberShop = 'showMemberShop',
      enablePlayAll = 'enablePlayAll',
      enableTapDm = 'enableTapDm',
      setSystemBrightness = 'setSystemBrightness',
      downloadPath = 'downloadPath',
      followOrderType = 'followOrderType',
      enableImgMenu = 'enableImgMenu',
            showDynDispute = 'showDynDispute',
      touchSlopH = 'touchSlopH',
      tabSwipeVelocityThreshold = 'tabSwipeVelocityThreshold',
      tabSwipeDistanceThresholdPercent =
          'tabSwipeDistanceThresholdPercent',
      floatingNavBar = 'floatingNavBar',
      removeSafeArea = 'removeSafeArea',
      verticalFullscreenBottomBarSafeArea =
          'verticalFullscreenBottomBarSafeArea',
      verticalFullscreenBottomBarSafeHeight =
          'verticalFullscreenBottomBarSafeHeight',
      angleDegrees = 'angleDegrees',
      liveStream = 'liveStream';

  static const String minimizeOnExit = 'minimizeOnExit',
      windowSize = 'windowSize',
      windowPosition = 'windowPosition',
      isWindowMaximized = 'isWindowMaximized',
      showWindowTitleBar = 'showWindowTitleBar',
      desktopVolume = 'desktopVolume',
      showTrayIcon = 'showTrayIcon',
      uiScale = 'uiScale';

  static const String subtitlePreferenceV2 = 'subtitlePreferenceV2',
      enableDragSubtitle = 'enableDragSubtitle',
      subtitlePaddingH = 'subtitlePaddingH',
      subtitlePaddingB = 'subtitlePaddingB',
      subtitleBgOpacity = 'subtitleBgOpaticy',
      subtitleStrokeWidth = 'subtitleStrokeWidth',
      subtitleFontScale = 'subtitleFontScale',
      subtitleFontScaleFS = 'subtitleFontScaleFS',
      subtitleFontWeight = 'subtitleFontWeight';

  static const String showAdvancedSettings = 'showAdvancedSettings',
      webdavUri = 'webdavUri',
      webdavUsername = 'webdavUsername',
      webdavPassword = 'webdavPassword',
      webdavDirectory = 'webdavDirectory';

  static const String enableSponsorBlock = 'enableSponsorBlock',
      blockSettings = 'blockSettings',
      blockLimit = 'blockLimit',
      blockColor = 'blockColor',
      blockUserID = 'blockUserID',
      blockToast = 'blockToast',
      blockServer = 'blockServer',
      blockTrack = 'blockTrack';

  static const String enableShowDanmaku = 'enableShowDanmaku',
      rememberDanmakuSwitchState = 'rememberDanmakuSwitchState',
      enableShowLiveDanmaku = 'enableShowLiveDanmaku',
      pipNoDanmaku = 'pipNoDanmaku',
      showVipDanmaku = 'showVipDanmaku',

// 旧布尔键继续保留，只用于兼容旧配置。
mergeDanmaku = 'mergeDanmaku',

// 新版重复弹幕合并模式。
danmakuMergeMode = 'danmakuMergeMode',

// 高频置顶合并参数。
burstDanmakuTriggerCount = 'burstDanmakuTriggerCount',
burstDanmakuWindowSeconds = 'burstDanmakuWindowSeconds',
burstDanmakuCooldownSeconds = 'burstDanmakuCooldownSeconds',
burstDanmakuFontScale = 'burstDanmakuFontScale',

danmakuWeight = 'danmakuWeight',
  highLikeDanmakuThreshold = 'highLikeDanmakuThreshold',
      danmakuBlockType = 'danmakuBlockType',
      danmakuShowArea = 'danmakuShowArea',
      danmakuOpacity = 'danmakuOpacity',
      danmakuChineseFontFile = 'danmakuChineseFontFile',
      danmakuChineseFontName = 'danmakuChineseFontName',
      danmakuEnglishFontFile = 'danmakuEnglishFontFile',
      danmakuEnglishFontName = 'danmakuEnglishFontName',
      danmakuFontScale = 'danmakuFontScale',
      danmakuFontScaleFS = 'danmakuFontScaleFS',
      danmakuDuration = 'danmakuDuration',
      danmakuStaticDuration = 'danmakuStaticDuration',
      danmakuMassiveMode = 'danmakuMassiveMode',
      liveDanmakuMassiveMode = 'liveDanmakuMassiveMode',
      danmakuFixedV = 'danmakuFixedV',
      danmakuStatic2Scroll = 'danmakuStatic2Scroll',
      danmakuLineHeight = 'danmakuLineHeight',
      danmakuStrokeWidth = 'strokeWidth',
  danmakuShadowRadius = 'danmakuShadowRadius',
      danmakuFontWeight = 'fontWeight';

  static const String systemProxyHost = 'systemProxyHost',
      systemProxyPort = 'systemProxyPort';

  static const String themeMode = 'themeMode',
      defaultTextScale = 'textScale',
      dynamicColor = 'dynamicColor',
      themeColorMode = 'themeColorMode',
      customColor = 'customColor',
      customPrimarySeed = 'customPrimarySeed',
      customSecondarySeed = 'customSecondarySeed',
      customTertiarySeed = 'customTertiarySeed',
      customThemeTonePrefix = 'customThemeTone',
      customThemeColorAssignments = 'customThemeColorAssignments',
      displayMode = 'displayMode',
      replyFontSize = 'replyFontSize',
      collapsedReplyFontScale = 'collapsedReplyFontScale',
      replyLineSpacingScale = 'replyLineSpacingScale',
      smallCardWidth = 'smallCardWidth',
      recommendCardWidth = 'recommendCardWidth',
      homeCardAspectRatio = 'homeCardAspectRatio',
      recommendDurationInStatRow = 'recommendDurationInStatRow',
      recommendStatSpacing = 'recommendStatSpacing',
      cardRadius = 'cardRadius',
      homeTabBarHeight = 'homeTabBarHeight',
      legacyBottomBarBottomPadding = 'legacyBottomBarBottomPadding',
      verticalScrollInertiaScale = 'verticalScrollInertiaScale',
verticalScrollDecelerationScale = 'verticalScrollDecelerationScale',
      dynamicsWaterfallFlow = 'dynamicsWaterfallFlow',
      upPanelPosition = 'upPanelPosition',
      dynamicsShowAllFollowedUp = 'dynamicsShowAllFollowedUp',
      useSideBar = 'useSideBar',
      enableMYBar = 'enableMYBar',
      hideTopBar = 'hideSearchBar',
      hideBottomBar = 'hideTabBar',
      barHideType = 'barHideType',
      tabBarSort = 'tabBarSort',
      dynamicBadgeMode = 'dynamicBadgeMode',
      msgBadgeMode = 'msgBadgeMode',
      msgUnReadTypeV2 = 'msgUnReadTypeV2',
      navBarSort = 'navBarSort',
      tempPlayerConf = 'tempPlayerConf',
      reduceLuxColor = 'reduceLuxColor',
      liveCdnUrl = 'liveCdnUrl',
      saveReply = 'saveReply';
}

abstract final class LocalCacheKey {
  static const String historyPause = 'historyPause',
      historyPauseAccountMid = 'historyPauseAccountMid',
      historyArchiveLastAt = 'historyArchiveLastAt',
      historyArchiveLatestViewAt = 'historyArchiveLatestViewAt',
      historyArchiveAccountCutoffs = 'historyArchiveAccountCutoffs',
      historyArchiveAccountLastAts = 'historyArchiveAccountLastAts',
      mineQuoteIndex = 'mineQuoteIndex',
      lastClipboardLink = 'lastClipboardLink',
      rcmdHomeSnapshot = 'rcmdHomeSnapshot',
      blackMids = 'blackMids',
      danmakuFilterRules = 'danmakuFilterRules',
      mixinKey = 'mixinKey',
      timeStamp = 'timeStamp',
      buvid = 'buvid';
}

abstract final class VideoBoxKey {
  static const String playRepeat = 'playRepeat',
      playSpeedDefault = 'playSpeedDefault',
      longPressSpeedDefault = 'longPressSpeedDefault',
      speedsList = 'speedsList',
      cacheVideoFit = 'cacheVideoFit';
}
